#!/usr/bin/env node
// schema/ → src/generated/: the only way anything Python-owned reaches the TS side.
//
// The Python package is the SSOT (illustration/schema.py, the provider classes, the licence
// tables). `illustration export-schema` writes the committed `schema/` directory at the repo
// root; this script turns it into TypeScript:
//
//   schema/image-result.schema.json  →  src/generated/image-result.ts   (Zod + types)
//   schema/sources.json              →  src/generated/sources.ts        (the registry as data)
//   schema/constants.json            →  src/generated/constants.ts      (rights fields, licences, defaults)
//
// We consume the committed JSON rather than reaching into Python, so `ts/` builds with no Python
// toolchain and depends only on the JSON contract (the walkthru D10 shape). The parity fixtures
// under schema/fixtures/ are NOT generated into code — the vitest suite reads them directly.
//
// Regenerate after the Python side changes:
//   1. (Python) `illustration export-schema` — pinned by tests/test_schema_export.py
//   2. (TS)     `npm run codegen`            — pinned by src/codegen.test.ts via `--check`

import $RefParser from '@apidevtools/json-schema-ref-parser';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { jsonSchemaToZod } from 'json-schema-to-zod';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TS_ROOT = resolve(__dirname, '..');
const REPO_ROOT = resolve(TS_ROOT, '..');
const SCHEMA_DIR = resolve(REPO_ROOT, 'schema');
const OUT_DIR = resolve(TS_ROOT, 'src/generated');

const HEADER = (source) =>
  `// GENERATED by ts/scripts/codegen.mjs from schema/${source} — do not edit.\n` +
  '// The Python package is the SSOT; run `illustration export-schema` then `npm run codegen`.\n\n';

class CodegenError extends Error {}

function readJson(name) {
  const path = resolve(SCHEMA_DIR, name);
  if (!existsSync(path)) {
    throw new CodegenError(`missing ${path}\nRun \`illustration export-schema\` first.`);
  }
  return JSON.parse(readFileSync(path, 'utf8'));
}

async function imageResultModule() {
  // json-schema-to-zod renders unresolved `$ref`s as z.any(); inline them first.
  const schema = await $RefParser.dereference(readJson('image-result.schema.json'));
  const code = jsonSchemaToZod(schema, {
    name: 'imageResultSchema',
    module: 'esm',
    type: 'ImageResult',
  });
  return (
    HEADER('image-result.schema.json') +
    code +
    '\n' +
    '// The pre-parse twin: fields the schema defaults are OPTIONAL here (walkthru#24).\n' +
    'export type ImageResultInput = z.input<typeof imageResultSchema>\n'
  );
}

function sourcesModule() {
  const records = readJson('sources.json');
  return (
    HEADER('sources.json') +
    "import type { SourceRecord } from '../source-record';\n\n" +
    '/** One record per source registered on the Python side, in registration order. */\n' +
    `export const SOURCE_RECORDS: readonly SourceRecord[] = ${JSON.stringify(records, null, 2)};\n`
  );
}

function constantsModule() {
  const constants = readJson('constants.json');
  return (
    HEADER('constants.json') +
    '/** Rights fields, licence tables, façade defaults and credential lookups. */\n' +
    `export const CONSTANTS = ${JSON.stringify(constants, null, 2)} as const;\n`
  );
}

/** Every generated module, keyed by its path under src/generated/. Exported so the drift-guard
 *  test and the CLI share one code path. */
export async function buildModules() {
  return {
    'image-result.ts': await imageResultModule(),
    'sources.ts': sourcesModule(),
    'constants.ts': constantsModule(),
  };
}

export function committedModule(name) {
  const path = resolve(OUT_DIR, name);
  return existsSync(path) ? readFileSync(path, 'utf8') : null;
}

export { OUT_DIR, SCHEMA_DIR };

if (resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  try {
    const modules = await buildModules();
    if (check) {
      const stale = Object.keys(modules).filter((n) => committedModule(n) !== modules[n]);
      if (stale.length) {
        console.error(`codegen: STALE ${stale.join(', ')} — run \`npm run codegen\` and commit.`);
        process.exit(1);
      }
      console.log('codegen: generated modules are up to date ✓');
    } else {
      mkdirSync(OUT_DIR, { recursive: true });
      for (const [name, text] of Object.entries(modules)) {
        writeFileSync(resolve(OUT_DIR, name), text);
        console.log(`codegen: wrote src/generated/${name}`);
      }
    }
  } catch (err) {
    console.error(`codegen: ${err.message}`);
    process.exit(1);
  }
}
